language: node_js
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- npm run build-lib
before_deploy:
- cd dist/firebaseui-angular-library
deploy:
  provider: npm
  email: "\\info@rjenni.ch"
  skip_cleanup: true
  api_key:
    secure: fgSXr8KSW2+2epBxVai3anaaMgwtGvBImbCUeDAg2f6GPFU7VLa9Y2veFepwvHwS1ejjyR5Wia45NLg4byhcuOkYPLFLW8GR7iry5xPwNlur3yb4Tzck/5WFY2v0LaMqeCbS7Li5l3P+ypxxfqgPrRFW9VDQlgrPN2pQIGi8qmyr4CQsy82qsdkutNeiETWos5wFNS0i2r4t81nmQsFoadsI5Cifo6CnH+xDNCdPJAhR8xASJUwzucaspke1O6gfDvZNYHx1LAZqCLlIM70DW1FEsYKU4V/oj2hU1ZwKtALVIWGIsb7Lm3TJ5kgm5zE462DpAuRBwoMQKqrh4KX1X4OYe6duFKrwM4Ik+lbAVcajBkMURtc5GLkVZ3Vt8yYI2dpOCC4b1LWuGKotwkylCds1Oa7eXMTkqnDl1mU6S0FwqyG/0Bt5E3/L1wirRmwfj+aWx8nZPsZuX9N7bL9qU8ePV8dtBM7JxU0wjiQLqfINSkRXLvJOziTuwwkEiFBV1gNv6IpgkEBmJYXQBQhXMSS4XdRReWXPQfmR1lMO1qypgLW/P1vBSpfWelnSUkksoPvQncyX301OY5CaiGRcNK6wPZ3/HG/3xPHQ95zsCQPqg1cRjgxUZxBqpknm7SAQfny1m0H/khVHW5IUk86oqKHH16C1iM8HRYoAQ766F9M=
  on:
    tags: true
    repo: RaphaelJenni/FirebaseUI-Angular
notifications:
  email:
    recipients:
    - "$EMAIL"
    on_failure: always
    on_success: always
